### ISSUE TITLE
What is the (*) for?? 

### ISSUE THREAD

**Issue by ShuvenduBikash** [eriklindernoren/PyTorch-GAN#10]
https://github.com/eriklindernoren/PyTorch-GAN/blob/9e3ac57d2a0480ded339841dda18b13e2645987f/implementations/gan/gan.py#L47

**Comment by eriklindernoren** [comment]
That's for unpacking a python list (e.g. `*[1,2,3] == 1,2,3`). It's helpful when defining sequential models in PyTorch. 

E.g.
```python
layers = [nn.Conv2d(3, 128, kernel_size=3), nn.LeakyReLU(0.2, inplace=True)]
model = nn.Sequential(*layers)
```
Which is the same as:
```python
model = nn.Sequential(
    nn.Conv2d(3, 128, kernel_size=3),
    nn.LeakyReLU(0.2, inplace=True)
)
```

**Comment by ShuvenduBikash** [comment]
Thank you 👍
