### ISSUE TITLE
Channel first issue

### ISSUE THREAD

**Issue by ShuvenduBikash** [eriklindernoren/PyTorch-GAN#11]
Where have you told pytorch that you are going to use channel first image? Previously I used channel last image with pytorch.

https://github.com/eriklindernoren/PyTorch-GAN/blob/f4c14d1daf86c6c05d8d36c53bc8e7587f00c206/implementations/cgan/cgan.py#L34

**Comment by eriklindernoren** [comment]
It's channel first by default. See https://pytorch.org/docs/master/nn.html
