### ISSUE TITLE
Why adding channels here with input size?

### ISSUE THREAD

**Issue by ShuvenduBikash** [eriklindernoren/PyTorch-GAN#12]
https://github.com/eriklindernoren/PyTorch-GAN/blob/3a009005f1a45f9f1547b89005933cd6d5ca865c/implementations/ccgan/models.py#L47

**Comment by eriklindernoren** [comment]
I add a low resolution version of the image to be generated as input to the generator. Similarly to what they suggest doing in the paper. This image has three channels and these channels will therefore have to be added to the 128 output filters from the layer before it.  This image how this image is added to the generator in the paper. 

![ccgan](https://user-images.githubusercontent.com/7977505/40320982-d583b4b4-5d2d-11e8-9ce5-64bfe50094f9.png)
