### ISSUE TITLE
patchGAN

### ISSUE THREAD

**Issue by ShuvenduBikash** [eriklindernoren/PyTorch-GAN#15]
What exactly is it? Here can I learn about it?

https://github.com/eriklindernoren/PyTorch-GAN/blob/3a009005f1a45f9f1547b89005933cd6d5ca865c/implementations/pix2pix/pix2pix.py#L54

**Comment by eriklindernoren** [comment]
I would Google it. They briefly describe it in the paper as well. Feel free to mail me with these kinds of questions instead of opening issues. Try to keep issues to implementation problems please. Thanks.
