### ISSUE TITLE
Variable object has no attribute 'item '

### ISSUE THREAD

**Issue by ayushmangupta1990** [eriklindernoren/PyTorch-GAN#16]
https://github.com/eriklindernoren/PyTorch-GAN/blob/3a009005f1a45f9f1547b89005933cd6d5ca865c/implementations/gan/gan.py#L154

Traceback (most recent call last):
  File "gan/gan.py", line 154, in <module>
    d_loss.item(), g_loss.item()))
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 67, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'item'

**Comment by eriklindernoren** [comment]
I think you have to update PyTorch to fix this. I have added PyTorch 0.4.0 to requirements so you can try:

`sudo pip3 install -r requirements.txt`
