### ISSUE TITLE
I was denied to access your git

### ISSUE THREAD

**Issue by brainBY** [eriklindernoren/PyTorch-GAN#19]
I can't git clone https://github.com/eriklindernoren/PyTorch-GAN
Error message is below.
fatal: could not create work tree dir 'PyTorch-GAN'

Why does this error happen?

**Comment by eriklindernoren** [comment]
Maybe you don't have write permissions in the directory where you're trying to clone the repo?

See: https://stackoverflow.com/questions/16376035/fatal-could-not-create-work-tree-dir-kivy

**Comment by brainBY** [comment]
네이버 메일 앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Erik Linder-Norén" <notifications@github.com>
받는사람: "eriklindernoren/PyTorch-GAN" <PyTorch-GAN@noreply.github.com>
참조: "bylee" <yhungkr@naver.com>,"Author" <author@noreply.github.com>
날짜: 2018.09.01 오전 04:12:30
제목: Re: [eriklindernoren/PyTorch-GAN] I was denied to access your git (#19)

Maybe you don't have write permissions in the directory where you're trying to clone the repo?
See: https://stackoverflow.com/questions/16376035/fatal-could-not-create-work-tree-dir-kivy

**Comment by eriklindernoren** [comment]
I'll close this one because of inactivity.
