### ISSUE TITLE
WGAN-GP gradient penalty not calculated correctly

### ISSUE THREAD

**Issue by sootlasten** [eriklindernoren/PyTorch-GAN#20]
The L2 norm of the gradient penalty term in WGAN-GP should be calculated across all dimensions of an image, but the current implementation calculates it across each dimension of an image separately (i.e., the absolute value of each pixel in an image is calculated). 

Indeed, in the following line, `gradients` is a tensor of size `(batch_size, nb_channels, img_width, img_height)`:
```
gradient_penalty = ((gradients.norm(2, dim=1) - 1) ** 2).mean()
```

To solve the issue, the 4-dimensional tensor containing the gradients should be flattened across the last 3 dimensions:
```
gradients = gradients.view(real_samples.size(0), -1)
gradient_penalty = ((gradients.norm(2, dim=1) - 1) ** 2).mean()
```

**Comment by Oktai15** [comment]
@eriklindernoren It's essential issue -- please, fix it :)
