### ISSUE TITLE
SRGAN's data download link address has expired

### ISSUE THREAD

**Issue by MrLinNing** [eriklindernoren/PyTorch-GAN#24]

**Comment by YueXiNPU** [comment]
I have also meet the same problem.

**Comment by kdreher** [comment]
I have the same problem
Are there maybe other datasets which one could use for running the example?

**Comment by eriklindernoren** [comment]
Hi. If you visit the dataset's web page you will see other options. http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html
