### ISSUE TITLE
Issue in CycleGan-Pix2Pix while calling  Discriminator()

### ISSUE THREAD

**Issue by kkose** [eriklindernoren/PyTorch-GAN#3]
While calling Discriminator() from models.py in cycleGan and pix2pix, I get a syntax error response as ;

```
Traceback (most recent call last):
  File "cyclegan.py", line 15, in <module>
    from models import *
  File "./PyTorch-GAN/implementations/cyclegan/models.py", line 167
    *discriminator_block(64, 128, 2, True),
    ^
SyntaxError: invalid syntax
```

This happens with both python3 and python2.7. 
Looks like dereferencing does not work and I could not find a way to make it work. 

Any bits of advice?

Thanks

**Comment by eriklindernoren** [comment]
That's strange. I'm using Python 3.6.3 and it's working fine for me. What 3.x.x version are you using?

Not sure if this will work (since it's also unpacking a list) but you could try:

```python
class Discriminator(nn.Module):
    def __init__(self, in_channels=3):
        super(Discriminator, self).__init__()

        def discriminator_block(in_filters, out_filters, stride, normalize):
            """Returns layers of each discriminator block"""
            layers = [nn.Conv2d(in_filters, out_filters, 3, stride, 1)]
            if normalize:
                layers.append(nn.InstanceNorm2d(out_filters))
            layers.append(nn.LeakyReLU(0.2, inplace=True))
            return layers

        layers = []
        layers.extend(discriminator_block(in_cannels, 64, 2, False))
        layers.extend(discriminator_block(64, 128, 2, True))
        layers.extend(discriminator_block(128, 256, 2, True))
        layers.extend(discriminator_block(256, 512 , 2, True))
        layers.append(nn.Conv2d(512, 1, 3, 1, 1))
        self.model = nn.Sequential(*layers)

    def forward(self, img):
        return self.model(img)
```
If not you might have to add the layers one by one.

**Comment by kkose** [comment]
works like a charm. Two small issues
(i) There is a typo in the above code. Instead of "in_cannels"  it should be "in_channels" 
(ii) As you are using stride=2 for 4 times so I think line#54 in "cyclegan.py" needs to be changed as 
`patch_h, patch_w = int(opt.img_height / 2**4), int(opt.img_width / 2**4)`

By the way, just wanted to confirm, the code also works for python2.7 too (with a few simple edits). I will try to run an experiment to see if the results also make sense with python2.7 :smile: 

Thanks again
