### ISSUE TITLE
no results of CycleGAN

### ISSUE THREAD

**Issue by SummerHuiZhang** [eriklindernoren/PyTorch-GAN#30]
I run CycleGAN following all  commands the author gave. But there is empty in images and saved_models. I tested that the cyclegan.py didn't enter the 140 line  "for i, batch in enumerate(dataloader):".
Any advices is appreciated.

**Comment by ddwell** [comment]
I am having the exact same issue as @SummerHuiZhang

**Comment by ddwell** [comment]
@SummerHuiZhang I think the issue is here, try removing the slashes or rearrange the folder structure. 
![image](https://user-images.githubusercontent.com/25105581/50218760-99792100-03bf-11e9-94b8-e497c360dc51.png)

**Comment by eriklindernoren** [comment]
I'll close this due to inactivity.
