### ISSUE TITLE
CycleGan error: weight of size [64, 3, 7, 7], expected input[1, 1, 262, 262] to have 3 channels, but got 1 channels instead

### ISSUE THREAD

**Issue by morawi** [eriklindernoren/PyTorch-GAN#39]
I am having this error using `horse2zebra`, I have checked all the input images and they all have the size `[3, 265, 265]`, so, most probable that the error is caused by `G_AB(real_B)`.  I have, however, tried `cyclegan` with `cifar-100` and `monet2photo` and everything went fine. I am using `PyTorch 0.4` and `Python 3.6`.
```
line 157, in <module>
    loss_id_B = criterion_identity(G_AB(real_B), real_B)
...
Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 1, 262, 262] to have 3 channels, but got 1 channels instead
```

**Comment by eriklindernoren** [comment]
Hey. Hadn't seen this before testing cyclegan again today. Apparently `horse2zebra` contains grayscale images. I have added a grayscale to rgb conversion step in the dataloader which should fix your issue. If you pull the latest version you should be good.

**Comment by morawi** [comment]
@eriklindernoren Thanks, this will indeed solve the problem. In fact, I have removed all the grayscale images to make work. Not sure to what degree a mix of grayscale and color images would affect the results.
