### ISSUE TITLE
AttributeError: module 'torchvision.transforms' has no attribute 'Resize'

### ISSUE THREAD

**Issue by dylib** [eriklindernoren/PyTorch-GAN#4]
I'm running the `srgan.py` implementation and receive the following error:
```
Namespace(b1=0.5, b2=0.999, batch_size=1, channels=3, checkpoint_interval=-1, dataset_name='img_align_celeba', decay_epoch=100, epoch=0, hr_height=256, hr_width=256, lr=0.0002, n_cpu=8, n_epochs=200, sample_interval=100)
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /Users/Username/.torch/models/vgg19-dcbb9e9d.pth
100%|███████████████████████████████████████████| 574673361/574673361 [00:34<00:00, 16895858.86it/s]
Traceback (most recent call last):
  File "srgan.py", line 104, in <module>
    lr_transforms = [   transforms.Resize((opt.hr_height//4, opt.hr_height//4), Image.BICUBIC),
AttributeError: module 'torchvision.transforms' has no attribute 'Resize'
```
If you need any additional information let me know...

**Comment by eriklindernoren** [comment]
What version of `torchvision` are you using? Since `torchvision.transforms.Resize` is [visible in their docs](http://pytorch.org/docs/master/torchvision/transforms.html#torchvision.transforms.Resize) updating you package should solve your issue.

**Comment by dylib** [comment]
It seems `torchvision 0.1.9` was what got installed when using `sudo pip3 install -r requirements.txt`. I ran `sudo pip3 install torchvision --upgrade` which installed version `0.2.1` which did resolve the issue — thank you!

**Comment by minhaj3** [comment]
I was having the error: "AttributeError: 'module' object has no attribute 'Resize' ". I installed torchvision-0.2.0-py2.py3-none-any.whl from the wheel file available at https://download.pytorch.org/whl/cu90/torch_stable.html and it solved my problem. I was previously using torchvision==0.1.6 when the error occured.
