### ISSUE TITLE
The channel size does not match the broadcast channel size DCgans

### ISSUE THREAD

**Issue by RongKaiWeskerMA** [eriklindernoren/PyTorch-GAN#40]
tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 32, 32] doesn't match the broadcast shape [3, 32, 32]

When I was runing the DCGANS example, it gives me this error.

**Comment by aidiary** [comment]
MNIST has 1 channel.
I corrected  this way.

```
transforms.Normalize([0.5], [0.5])
```

**Comment by RongKaiWeskerMA** [comment]
Hi, I was trying to do this way: transforms.Normalize(0.5, 0.5), it still
gave me some error: too many indices for dimension 0. Is there any reason
for you to use square bracket to form a single element list to past the
parameters?

**Comment by eriklindernoren** [comment]
@RongKaiWeskerMA Thanks for pointing this out. Seems like newer PyTorch versions throws an exception for this. The number of elements for mean and standard deviation respectively should match the number of channels in the training images, so for MNIST it should be `transforms.Normalize([0.5], [0.5])`. I've updated all models that are applied to MNIST, so if you pull the latest version it should work.
