### ISSUE TITLE
2 small suggestions

### ISSUE THREAD

**Issue by Eurus-Holmes** [eriklindernoren/PyTorch-GAN#44]
1. It can be summarized in the chronological order of the papers rather than the first letter of the model so that it is easier to study the related development of GAN more clearly. 

2. It would be better if you can briefly summarize the connections and differences between the models in papers.

**Comment by eriklindernoren** [comment]
Sorry, but I have no plans for this at the moment. I would rather focus on adding more implementations to the repository. The second point especially would require almost `n^2` amount of work for each model added. I very much appreciate the suggestions though. :)
