### ISSUE TITLE
Are the two model acgan.py and sgan.py the same?

### ISSUE THREAD

**Issue by Eurus-Holmes** [eriklindernoren/PyTorch-GAN#45]
[acgan.py](https://github.com/eriklindernoren/PyTorch-GAN/blob/master/implementations/acgan/acgan.py)    --- [sgan.py](https://github.com/eriklindernoren/PyTorch-GAN/blob/master/implementations/sgan/sgan.py)

**Comment by eriklindernoren** [comment]
They are quite similar, but if you look at how the generators are defined you see that the ACGAN generator takes both noise and labels as input, while the SGAN generator only takes noise as input.

**Comment by Eurus-Holmes** [comment]
oh, I see, thanks!
