### ISSUE TITLE
WGAN implementation error

### ISSUE THREAD

**Issue by marued** [eriklindernoren/PyTorch-GAN#47]
In your WGAN implementation, you have your n-critique loop around the Generator learning when it should actually be around the Discriminator's. Critique stands for Discriminator.

**Comment by eriklindernoren** [comment]
The papers tells us that we should train the critic (discriminator) `n_critic` times for each `generator` update, just as WGAN is implemented here. The discriminator is updated on each batch but the generator is only updated every `n_critic` batch.

**Comment by marued** [comment]
A yes, sorry! I read too quickly and mistook the 'If' in the code for a 'for' loop.

**Comment by eriklindernoren** [comment]
No problem! :)
