### ISSUE TITLE
wgan-gp

### ISSUE THREAD

**Issue by rainerkelz** [eriklindernoren/PyTorch-GAN#5]
hi, i believe the implementation of wgan-gp is buggy. the interpolation in https://github.com/eriklindernoren/PyTorch-GAN/blob/8aff6caf1144501355c5cc8746b119a907edfe67/implementations/wgan_gp/wgan_gp.py#L124 uses a random number for each **pixel**, whereas the pseudocode in the paper says to use a random number for each **example**.

i believe the line should be replaced by
`alpha = Tensor(np.random.random(size=(real_samples.shape[0], 1, 1, 1)))`

**Comment by eriklindernoren** [comment]
Thanks. This is fixed in d2977bc.

**Comment by rainerkelz** [comment]
awesome! thank you!
