### ISSUE TITLE
About the Identity loss in cyclegan.py

### ISSUE THREAD

**Issue by LittleQuteSweetie** [eriklindernoren/PyTorch-GAN#59]
The source code of Identity loss is shown below:
`loss_id_A = criterion_identity(G_BA(real_A), real_A)`
`loss_id_B = criterion_identity(G_AB(real_B), real_B)`

This seems a little bit weird to me, maybe it should be:
`loss_id_A = criterion_identity(G_AB(real_A), real_A)`
`loss_id_B = criterion_identity(G_BA(real_B), real_B)`

**Comment by binli123** [comment]
I have the same concern.

**Comment by busekuz** [comment]
I think these issues from the original repo, especially the first one, might give you a better idea on what identity loss is.
[1](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/322), [2](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/pull/362#issuecomment-419733696)

**Comment by IvanFei** [comment]
G_BA: domain B -> domain A,
It wants to realize identity map, f(x) = x. 
In this case, If the input of G_BA is image in domain A (not in domain B), the output of G_BA should be the same as image in domain A. 

as the follow picture `Lconst`
![image](https://user-images.githubusercontent.com/24504559/68111681-adbc0300-ff2a-11e9-90e2-e761f54784be.png)

refer to [Unsupervised Cross-Domain Image Generation](https://arxiv.org/abs/1611.02200)
and [Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks](https://arxiv.org/abs/1703.10593)

**Comment by IvanFei** [comment]
G_BA: domain B -> domain A,
It wants to realize identity map, f(x) = x. 
In this case, If the input of G_BA is image in domain A (not in domain B), the output of G_BA should be the same as image in domain A. 

As is shown in the picture (below) -> `L_TID`
![image](https://user-images.githubusercontent.com/24504559/68112484-6171c280-ff2c-11e9-9111-da38c04dc3ce.png)


refer to [Unsupervised Cross-Domain Image Generation](https://arxiv.org/abs/1611.02200)
and [Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks](https://arxiv.org/abs/1703.10593)

detailed explanation: https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/322

**Comment by LittleQuteSweetie** [comment]
@IvanFei @busekuz 
Thanks for your answers!
They are very helpful, especially the picture; I think now I do understand the identity loss.

Best Regards,
LQS

**Comment by LittleQuteSweetie** [comment]
@IvanFei @busekuz
Thanks for your answers!
They are very helpful, especially the picture; I think now I do understand the identity loss.

Best Regards,
LQS
