### ISSUE TITLE
wgan issuse

### ISSUE THREAD

**Issue by Sophia-intel** [eriklindernoren/PyTorch-GAN#8]
when I run python3 wgan.py, appears      print ("[Epoch %d/%d] [Batch %d/%d] [D loss: %f] [G loss: %f]" % (epoch, opt.n_epochs,batches_done % len(dataloader), len(dataloader),d_loss.item(), gen_validity.item()))
ValueError: only one element tensors can be converted to Python scalars
how can i fix it?

**Comment by eriklindernoren** [comment]
I have encountered that issue before but it seems to run without a problem with the latest version. Maybe you can try and run `git pull` and see if that fixes the issue. Have you made any changes to the current implementation?

**Comment by Sophia-intel** [comment]
@eriklindernoren hey, it really works.Thanks!
