### ISSUE TITLE
WGAN-GP loss became large

### ISSUE THREAD

**Issue by xiaohai12** [eriklindernoren/PyTorch-GAN#87]
![image](https://user-images.githubusercontent.com/27256068/71826801-1cd6e480-309f-11ea-863f-c858a5773bbb.png)
Hey, I got a problem that the wassertein distance (=d_loss_real - d_loss_fake) increase during the training and became very large, anyone can help me with this?

**Comment by kapoorparul** [comment]
did you find a reason for this?

**Comment by supermarian** [comment]
I have the same problem. Have you figured it out?
